name: Linux CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run and kill
        run: |
          chmod +x ./gear
          ./gear & sleep 1
          pkill -f 'gear |gear$' -9
          echo $?
